//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBillingSuite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBC_ConfigFab
    {
        public System.Guid PKID { get; set; }
        public int ConfigurationKey { get; set; }
        public string KeyName { get; set; }
        public string KeyValue { get; set; }
        public string NotificationInfo { get; set; }
    }
}
