//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBillingSuite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlTemplateBase
    {
        public System.Guid pkid { get; set; }
        public string CaminhoXML { get; set; }
        public string NomeCampo { get; set; }
        public string Tipo { get; set; }
        public string TipoXML { get; set; }
        public string Formato { get; set; }
        public string TipoMetadado { get; set; }
        public Nullable<bool> Obrigatorio { get; set; }
        public Nullable<int> Posicao { get; set; }
    }
}
